// src/routes/admin/bookings/[id]/+page.svelte
<script lang="ts">
  export let data: any;

  const { booking, guides = [], guideUpdated = false } = data;

  const tour = booking?.Tour ?? null;
  const customer = booking?.User ?? null;

  const formatDateTime = (value?: string) => {
    if (!value) return "—";
    const d = new Date(value);
    if (Number.isNaN(d.getTime())) return value;
    return d.toLocaleString("en-GB", {
      day: "2-digit",
      month: "short",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit"
    });
  };

  const formatDate = (value?: string) => {
    if (!value) return "—";
    const d = new Date(value);
    if (Number.isNaN(d.getTime())) return value;
    return d.toLocaleDateString("en-GB", {
      day: "2-digit",
      month: "short",
      year: "numeric"
    });
  };

  const formatMoney = (value?: number | null) => {
    if (value === null || value === undefined) return "—";
    return `£${value.toFixed(2)}`;
  };

  const formatBookingRef = (id?: string) => {
    if (!id) return "—";
    const clean = id.replace(/[^A-Za-z0-9]/g, "");
    const short = clean.slice(-6).toUpperCase();
    return `OT-${short}`;
  };

  const bookingRef = formatBookingRef(booking?.id);

  const currentGuide =
    booking?.guideId && guides.length
      ? guides.find((g: any) => g.id === booking.guideId) ?? null
      : null;
</script>

<div class="page-shell space-y-6">
  <!-- Header -->
  <header class="page-header">
    <div>
      <h1 class="page-title">Booking details</h1>
      <p class="page-subtitle">
        Admin view of booking, customer, tour and guide assignment.
      </p>
    </div>

    <a href="/admin/bookings" class="btn-secondary text-xs">
      ← Back to bookings
    </a>
  </header>

  <!-- Top summary -->
  <section class="grid gap-6 md:grid-cols-[2fr,1.4fr]">
    <!-- Left: booking + customer + tour -->
    <div class="space-y-4">
      <!-- Booking summary -->
      <div class="card space-y-3">
        <div class="flex flex-wrap items-baseline justify-between gap-2">
          <div>
            <div class="text-meta">Booking reference</div>
            <div class="text-lg font-semibold">{bookingRef}</div>
            <div class="text-meta font-mono">{booking.id}</div>
          </div>

          <div class="space-y-1 text-right">
            <div class="text-meta">Status</div>
            {#if booking.status === "confirmed"}
              <span class="badge badge-active">Confirmed</span>
            {:else if booking.status === "cancel_requested"}
              <span class="badge badge-featured">Cancel requested</span>
            {:else if booking.status === "cancelled"}
              <span class="badge badge-inactive">Cancelled</span>
            {:else}
              <span class="badge badge-muted">
                {booking.status ?? "Pending"}
              </span>
            {/if}
          </div>
        </div>

        <div class="grid sm:grid-cols-3 gap-3 text-sm">
          <div>
            <div class="text-meta">Tour date</div>
            <div>{formatDate(booking.startDate ?? booking.createdAt)}</div>
          </div>
          <div>
            <div class="text-meta">Guests</div>
            <div>{booking.guests ?? "—"}</div>
          </div>
          <div>
            <div class="text-meta">Total / Paid</div>
            <div>
              {formatMoney(booking.totalAmount)} ·
              <span class="text-muted">
                Paid {formatMoney(booking.amountPaid)}
              </span>
            </div>
          </div>
        </div>
      </div>

      <!-- Customer -->
      <div class="card space-y-3">
        <h2 class="text-sm font-semibold">Customer</h2>
        {#if customer}
          <div class="space-y-1 text-sm">
            {#if customer.name}
              <div class="font-semibold">{customer.name}</div>
            {/if}
            <div class="text-meta">{customer.email}</div>
            {#if customer.mobile}
              <div class="text-meta">Mobile: {customer.mobile}</div>
            {/if}
          </div>
        {:else}
          <p class="text-muted text-sm">
            No linked customer record — booking may have been created manually.
          </p>
        {/if}
      </div>

      <!-- Tour -->
      {#if tour}
        <div class="card space-y-3">
          <h2 class="text-sm font-semibold">Tour</h2>
          <div class="space-y-1 text-sm">
            <div class="font-semibold">{tour.title}</div>
            {#if tour.summary}
              <p class="text-muted">{tour.summary}</p>
            {/if}
            <div class="flex flex-wrap gap-3 text-meta">
              {#if tour.durationDays}
                <span>
                  {tour.durationDays} day{tour.durationDays === 1 ? "" : "s"}
                </span>
              {/if}
              {#if tour.pickupTime}
                <span>Pickup time: {tour.pickupTime}</span>
              {/if}
              {#if tour.price}
                <span>From £{tour.price}</span>
              {/if}
            </div>
          </div>
        </div>
      {/if}
    </div>

    <!-- Right column: GUIDE ASSIGNMENT + admin controls -->
    <div class="space-y-4">
      <!-- ✅ GUIDE ASSIGNMENT CARD -->
      <section class="card space-y-4">
        <div class="flex items-center justify-between gap-2">
          <h2 class="text-sm font-semibold">Guide assignment</h2>
          {#if guideUpdated}
            <span class="badge badge-active text-[10px]">
              Guide updated
            </span>
          {/if}
        </div>

        <!-- Current guide summary -->
        {#if currentGuide}
          <div class="flex items-center gap-3 text-sm">
            {#if currentGuide.photoUrl}
              <img
                src={currentGuide.photoUrl}
                alt="Guide photo"
                class="h-10 w-10 rounded-full object-cover border"
              />
            {/if}
            <div>
              <div class="font-semibold">
                {currentGuide.firstName} {currentGuide.lastName}
              </div>
              <div class="text-meta">{currentGuide.email}</div>
            </div>
          </div>
        {:else}
          <p class="text-sm text-muted">
            No guide assigned to this booking yet.
          </p>
        {/if}

        <!-- Assignment form -->
        <form method="POST" action="?/assignGuide" class="space-y-3">
          <div class="space-y-1">
            <label for="guideId" class="field-label">
              Assign / change guide
            </label>
            <select
              id="guideId"
              name="guideId"
              class="select"
            >
              <option value="">
                — No guide assigned —
              </option>
              {#each guides as guide}
                <option
                  value={guide.id}
                  selected={booking.guideId === guide.id}
                >
                  {guide.firstName} {guide.lastName} ({guide.email})
                </option>
              {/each}
            </select>
          </div>

          <div class="flex items-center justify-between gap-2">
            <button type="submit" class="btn-secondary btn-sm">
              Save guide
            </button>
            <p class="text-meta">
              Updates are saved instantly and logged in booking history.
            </p>
          </div>
        </form>
      </section>

      <!-- Admin notes -->
      <section class="card space-y-3">
        <h2 class="text-sm font-semibold">Admin notes</h2>
        <form method="POST" action="?/updateNotes" class="space-y-2">
          <textarea
            name="adminNotes"
            rows="5"
            class="textarea"
          >{booking.adminNotes ?? ""}</textarea>
          <button type="submit" class="btn-secondary btn-sm">
            Save notes
          </button>
        </form>
      </section>

      <!-- Cancellation controls (if relevant) -->
      {#if booking.status === "cancel_requested"}
        <section class="card-danger space-y-3">
          <h2 class="text-sm font-semibold">Cancellation requested</h2>
          <p class="text-sm">
            The customer has requested to cancel this booking. Choose whether to
            confirm the cancellation or keep the booking active.
          </p>
          <div class="flex flex-wrap gap-2">
            <form method="POST" action="?/approveCancellation">
              <button type="submit" class="btn-danger btn-sm">
                Confirm cancellation
              </button>
            </form>
            <form method="POST" action="?/keepBooking">
              <button type="submit" class="btn-secondary btn-sm">
                Keep booking
              </button>
            </form>
          </div>
        </section>
      {/if}
    </div>
  </section>
</div>

// app/admin/bookings/[id]/page.tsx
// app/admin/bookings/[id]/page.tsx
import { notFound } from "next/navigation";
import Link from "next/link";
import { prisma } from "@/lib/prisma";

interface PageProps {
  params: { id: string };
}

export default async function AdminBookingDetailPage({ params }: PageProps) {
  const booking = await prisma.booking.findUnique({
    where: { id: params.id },
    include: {
      tour: true,
      user: true,
      guide: true,
      extras: {
        include: {
          extraOption: true,
        },
      },
    },
  });

  if (!booking) {
    notFound();
  }

  // Pricing calculations
  const basePrice = booking.tour.pricePerPerson * booking.guests;
  const extrasTotal = booking.extras.reduce((sum, e) => sum + e.totalPrice, 0);
  const total = basePrice + extrasTotal;
  const paid = booking.amountPaid ?? 0;
  const remaining = Math.max(total - paid, 0);

  const lastPaymentAt = booking.updatedAt;
  const lastPaymentAmount = paid;
  const lastPaymentType: "deposit" | "balance" | null =
    lastPaymentAmount === 0
      ? null
      : remaining === 0
      ? "balance"
      : "deposit";

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between gap-3">
        <div>
          <h1 className="text-xl font-semibold text-highland-ink">
            Booking details
          </h1>
          <p className="text-sm text-highland-ink/70">
            View booking #{booking.id.slice(0, 8)} for{" "}
            <span className="font-medium">
              {booking.user?.name || booking.user?.email || "Unknown customer"}
            </span>
          </p>
        </div>
        <div className="flex gap-2">
          <Link
            href={`/admin/bookings/${booking.id}/edit`}
            className="px-3 py-1 text-xs rounded-full border border-highland-gold text-highland-ink hover:bg-highland-gold hover:text-highland-offwhite transition"
          >
            Edit booking
          </Link>
          <Link
            href="/admin/bookings"
            className="px-3 py-1 text-xs rounded-full border border-highland-stone text-highland-ink hover:border-highland-gold hover:text-highland-gold transition"
          >
            Back to bookings
          </Link>
        </div>
      </div>

      {/* Summary card */}
      <div className="border border-highland-stone rounded-2xl p-4 bg-highland-offwhite space-y-3 text-sm">
        <div className="flex flex-wrap justify-between gap-3">
          <div>
            <div className="text-xs uppercase tracking-wide text-highland-ink/60">
              Tour
            </div>
            <div className="font-semibold text-highland-ink">
              {booking.tour.title}
            </div>
            <div className="text-xs text-highland-ink/60">
              {booking.guests} guest
              {booking.guests !== 1 && "s"} ·{" "}
              {booking.startDate.toLocaleDateString("en-GB", {
                day: "numeric",
                month: "short",
                year: "numeric",
              })}
            </div>
          </div>

          <div className="text-right">
            <div className="text-xs uppercase tracking-wide text-highland-ink/60">
              Status
            </div>
            <div className="inline-flex items-center rounded-full px-2 py-1 text-[11px] font-medium border border-highland-stone text-highland-ink">
              {booking.status}
            </div>
          </div>
        </div>

        <div className="grid gap-3 sm:grid-cols-3 mt-3">
          <div>
            <div className="text-xs uppercase tracking-wide text-highland-ink/60">
              Customer
            </div>
            <div className="text-sm text-highland-ink">
              {booking.user?.name || "Unknown"}
            </div>
            <div className="text-xs text-highland-ink/70">
              {booking.user?.email}
            </div>
          </div>

          <div>
            <div className="text-xs uppercase tracking-wide text-highland-ink/60">
              Guide
            </div>
            {booking.guide ? (
              <>
                <div className="text-sm text-highland-ink">
                  {booking.guide.firstName} {booking.guide.lastName}
                </div>
                <div className="text-xs text-highland-ink/70">
                  {booking.guide.email}
                </div>
              </>
            ) : (
              <div className="text-xs text-highland-ink/70">
                No guide assigned
              </div>
            )}
          </div>

          <div>
            <div className="text-xs uppercase tracking-wide text-highland-ink/60">
              Created
            </div>
            <div className="text-sm text-highland-ink">
              {booking.createdAt.toLocaleDateString("en-GB", {
                day: "numeric",
                month: "short",
                year: "numeric",
              })}
            </div>
            <div className="text-xs text-highland-ink/70">
              {booking.createdAt.toLocaleTimeString("en-GB", {
                hour: "2-digit",
                minute: "2-digit",
              })}
            </div>
          </div>
        </div>
      </div>

      {/* Payment summary */}
      <div className="border border-highland-stone rounded-2xl p-4 bg-highland-offwhite space-y-3 text-sm">
        <h2 className="text-sm font-semibold text-highland-ink">
          Payment summary
        </h2>
        <div className="grid gap-3 sm:grid-cols-4">
          <div>
            <div className="text-xs uppercase tracking-wide text-highland-ink/60">
              Base tour
            </div>
            <div className="text-sm text-highland-ink">
              £{basePrice.toFixed(2)}
            </div>
          </div>
          <div>
            <div className="text-xs uppercase tracking-wide text-highland-ink/60">
              Extras
            </div>
            <div className="text-sm text-highland-ink">
              £{extrasTotal.toFixed(2)}
            </div>
          </div>
          <div>
            <div className="text-xs uppercase tracking-wide text-highland-ink/60">
              Paid
            </div>
            <div className="text-sm text-highland-ink">
              £{lastPaymentAmount.toFixed(2)}
            </div>
            {lastPaymentType && (
              <div className="text-xs text-highland-ink/70">
                Last payment: {lastPaymentType} on{" "}
                {lastPaymentAt.toLocaleDateString("en-GB", {
                  day: "numeric",
                  month: "short",
                  year: "numeric",
                })}
              </div>
            )}
          </div>
          <div>
            <div className="text-xs uppercase tracking-wide text-highland-ink/60">
              Remaining
            </div>
            <div className="text-sm font-semibold text-highland-ink">
              £{remaining.toFixed(2)}
            </div>
          </div>
        </div>
      </div>

      {/* Extras list */}
      <div className="border border-highland-stone rounded-2xl p-4 bg-highland-offwhite space-y-3 text-sm">
        <h2 className="text-sm font-semibold text-highland-ink">
          Extras on this booking
        </h2>
        {booking.extras.length === 0 ? (
          <p className="text-xs text-highland-ink/70">
            No extras have been added to this booking.
          </p>
        ) : (
          <ul className="divide-y divide-highland-stone/60">
            {booking.extras.map((extra) => (
              <li
                key={extra.id}
                className="py-2 flex items-center justify-between gap-3"
              >
                <div>
                  <div className="text-sm text-highland-ink">
                    {extra.extraOption.name}
                  </div>
                  <div className="text-xs text-highland-ink/70">
                    Qty {extra.quantity} · £{extra.unitPrice.toFixed(2)} each
                  </div>
                </div>
                <div className="text-sm text-highland-ink font-medium">
                  £{extra.totalPrice.toFixed(2)}
                </div>
              </li>
            ))}
          </ul>
        )}
      </div>

      {/* Admin notes */}
      <div className="border border-highland-stone rounded-2xl p-4 bg-highland-offwhite space-y-2 text-sm">
        <h2 className="text-sm font-semibold text-highland-ink">Admin notes</h2>
        {booking.adminNotes ? (
          <p className="text-sm text-highland-ink/80 whitespace-pre-wrap">
            {booking.adminNotes}
          </p>
        ) : (
          <p className="text-xs text-highland-ink/70">
            No admin notes have been added to this booking yet.
          </p>
        )}
      </div>
    </div>
  );
}
