// app/admin/bookings/[id]/page.tsx
// app/admin/bookings/[id]/page.tsx
import { auth } from "@/lib/auth";
import { redirect, notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import Link from "next/link";

interface PageProps {
  params: { id: string };
}

// Server action to handle the update
async function updateBooking(formData: FormData) {
  "use server";

  const session = await auth();
  if (!session?.user || (session.user as any).role !== "ADMIN") {
    redirect("/auth/login");
  }

  const bookingId = (formData.get("bookingId") as string | null) ?? "";
  const startDateStr = (formData.get("startDate") as string | null)?.trim() ?? "";
  const guestsStr = (formData.get("guests") as string | null)?.trim() ?? "";
  const statusStr = (formData.get("status") as string | null)?.trim() ?? "";

  if (!bookingId) {
    redirect("/admin/bookings");
  }

  const guests = Number(guestsStr || 0);
  if (!startDateStr || !guests || guests <= 0) {
    // In a full version we’d show validation errors; for now just bounce back
    redirect(`/admin/bookings/${bookingId}/edit`);
  }

  const startDate = new Date(startDateStr); // YYYY-MM-DD → Date

  // Cast status into your enum; if invalid, fall back to PENDING
  const allowedStatuses = ["PENDING", "CONFIRMED", "CANCELLED"] as const;
  const status =
    allowedStatuses.includes(statusStr as any) ? statusStr : "PENDING";

  await prisma.booking.update({
    where: { id: bookingId },
    data: {
      startDate,
      guests,
      status: status as any,
    },
  });

  redirect("/admin/bookings");
}

export default async function EditBookingPage({ params }: PageProps) {
  const session = await auth();
  if (!session?.user || (session.user as any).role !== "ADMIN") {
    redirect("/auth/login");
  }

  const booking = await prisma.booking.findUnique({
    where: { id: params.id },
    include: {
      tour: true,
      user: true,
    },
  });

  if (!booking) {
    notFound();
  }

  const startDate = new Date(booking.startDate);
  const startDateInput = startDate.toISOString().slice(0, 10); // YYYY-MM-DD

  const total = booking.totalAmount;
  const paid = booking.amountPaid;
  const remaining = Math.max(total - paid, 0);

  return (
    <div className="space-y-5">
      <header className="space-y-1">
        <p className="text-xs text-highland-ink/60">
          <Link
            href="/admin/bookings"
            className="underline underline-offset-2 text-highland-gold"
          >
            ← Back to bookings
          </Link>
        </p>
        <h1 className="text-2xl font-semibold text-highland-ink">
          Edit booking
        </h1>
        <p className="text-sm text-highland-ink/70">
          {booking.tour.title} ·{" "}
          {booking.user?.email ?? "Unknown customer"}
        </p>
      </header>

      <div className="grid md:grid-cols-[2fr,1.5fr] gap-5">
        {/* Editable core booking fields */}
        <form
          action={updateBooking}
          className="border border-highland-stone rounded-2xl bg-highland-offwhite p-4 space-y-4 text-sm"
        >
          <input type="hidden" name="bookingId" value={booking.id} />

          <div className="space-y-1">
            <label
              htmlFor="startDate"
              className="block text-xs font-medium text-highland-ink"
            >
              Tour date
            </label>
            <input
              id="startDate"
              name="startDate"
              type="date"
              defaultValue={startDateInput}
              className="w-full rounded-xl border border-highland-stone bg-highland-stone/10 px-3 py-2 text-sm text-highland-ink focus:outline-none focus:ring-1 focus:ring-highland-gold"
            />
            <p className="text-[11px] text-highland-ink/60">
              Update the scheduled date for this booking.
            </p>
          </div>

          <div className="space-y-1">
            <label
              htmlFor="guests"
              className="block text-xs font-medium text-highland-ink"
            >
              Guests
            </label>
            <input
              id="guests"
              name="guests"
              type="number"
              min={1}
              defaultValue={booking.guests}
              className="w-full rounded-xl border border-highland-stone bg-highland-stone/10 px-3 py-2 text-sm text-highland-ink focus:outline-none focus:ring-1 focus:ring-highland-gold"
            />
            <p className="text-[11px] text-highland-ink/60">
              Adjust the number of guests traveling on this booking.
            </p>
          </div>

          <div className="space-y-1">
            <label
              htmlFor="status"
              className="block text-xs font-medium text-highland-ink"
            >
              Status
            </label>
            <select
              id="status"
              name="status"
              defaultValue={booking.status as any}
              className="w-full rounded-xl border border-highland-stone bg-highland-stone/10 px-3 py-2 text-sm text-highland-ink focus:outline-none focus:ring-1 focus:ring-highland-gold"
            >
              <option value="PENDING">Pending</option>
              <option value="CONFIRMED">Confirmed</option>
              <option value="CANCELLED">Cancelled</option>
            </select>
            <p className="text-[11px] text-highland-ink/60">
              Use this to manually confirm or cancel a booking.
            </p>
          </div>

          <button
            type="submit"
            className="inline-flex items-center justify-center rounded-full bg-highland-gold text-highland-offwhite px-5 py-2 text-xs font-semibold hover:brightness-110"
          >
            Save changes
          </button>
        </form>

        {/* Read-only summary / context */}
        <aside className="space-y-3 text-sm">
          <div className="border border-highland-stone rounded-2xl bg-highland-offwhite p-4 space-y-2">
            <h2 className="text-sm font-semibold text-highland-ink">
              Booking summary
            </h2>
            <p className="text-xs text-highland-ink/70">
              Booking ID: {booking.id}
            </p>
            <p className="text-xs text-highland-ink/70">
              Created:{" "}
              {new Date(booking.createdAt).toLocaleString("en-GB", {
                day: "2-digit",
                month: "2-digit",
                year: "numeric",
                hour: "2-digit",
                minute: "2-digit",
              })}
            </p>
            <p className="text-xs text-highland-ink/70">
              Customer: {booking.user?.email ?? "Unknown"}
            </p>
            <p className="text-xs text-highland-ink/70">
              Tour: {booking.tour.title}
            </p>
          </div>

          <div className="border border-highland-stone rounded-2xl bg-highland-offwhite p-4 space-y-2 text-xs text-highland-ink/80">
            <h3 className="text-sm font-semibold text-highland-ink">
              Payment overview
            </h3>
            <p className="flex justify-between">
              <span>Total</span>
              <span className="font-semibold">£{total.toFixed(2)}</span>
            </p>
            <p className="flex justify-between">
              <span>Paid</span>
              <span className="font-semibold">£{paid.toFixed(2)}</span>
            </p>
            <p className="flex justify-between">
              <span>Outstanding</span>
              <span className="font-semibold">£{remaining.toFixed(2)}</span>
            </p>
            <p className="text-[11px] text-highland-ink/60 pt-1">
              To adjust amounts, you can either process a manual payment through
              the mock payment flow or extend this form later to edit payment
              details.
            </p>
          </div>
        </aside>
      </div>
    </div>
  );
}

// src/routes/admin/options/[id]/+page.svelte
<script lang="ts">
  export let data: any;
  export let form: any;

  const option = data.option;

  const effectiveValues = form?.values ?? option;

  const formatDateTime = (value?: string) => {
    if (!value) return "—";
    const d = new Date(value);
    if (Number.isNaN(d.getTime())) return value;
    return d.toLocaleString("en-GB", {
      day: "2-digit",
      month: "short",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit"
    });
  };
</script>

<div class="max-w-3xl mx-auto px-4 py-10 space-y-6">
  <header class="flex items-center justify-between gap-4">
    <div>
      <h1 class="text-2xl font-semibold">Edit extra option</h1>
      <p class="text-sm text-slate-400 mt-1">
        Option ID:
        <span class="font-mono">{option.id}</span>
      </p>
    </div>
    <a
      href="/admin/options"
      class="text-sm underline underline-offset-2 hover:no-underline text-slate-300"
    >
      ← Back to options
    </a>
  </header>

  <!-- Edit form -->
  <form
    method="POST"
    action="?/save"
    class="space-y-6 rounded-xl border border-slate-800 bg-slate-900/60 p-6"
  >
    {#if form?.message}
      <p class="text-sm text-red-300 mb-2">
        {form.message}
        {#if form.dbError}
          <span class="block text-[11px] text-red-400 mt-1">
            {form.dbError}
          </span>
        {/if}
      </p>
    {/if}

    <div class="space-y-2">
      <label class="text-sm font-medium" for="name">Name</label>
      <input
        id="name"
        name="name"
        type="text"
        class="w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm outline-none focus:border-emerald-400"
        value={effectiveValues.name ?? ""}
        required
      />
    </div>

    <div class="space-y-2">
      <label class="text-sm font-medium" for="description">Description</label>
      <textarea
        id="description"
        name="description"
        rows="3"
        class="w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm outline-none focus:border-emerald-400"
        placeholder="Short description of what this option includes…"
      >{effectiveValues.description ?? ""}</textarea>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm">
      <div class="space-y-2">
        <label class="text-sm font-medium" for="price">Price (£)</label>
        <input
          id="price"
          name="price"
          type="number"
          min="0"
          step="1"
          class="w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm outline-none focus:border-emerald-400"
          value={effectiveValues.price ?? ""}
        />
      </div>

      <div class="space-y-2">
        <label class="text-sm font-medium" for="chargeType">Charge type</label>
        <select
          id="chargeType"
          name="chargeType"
          class="w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm outline-none focus:border-emerald-400"
        >
          <option
            value="PerPerson"
            selected={effectiveValues.chargeType !== "PerTour"}
          >
            Per person
          </option>
          <option
            value="PerTour"
            selected={effectiveValues.chargeType === "PerTour"}
          >
            Per tour
          </option>
        </select>
      </div>

      <div class="space-y-2">
        <label class="text-sm font-medium" for="isActive">Status</label>
        <select
          id="isActive"
          name="isActive"
          class="w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm outline-none focus:border-emerald-400"
        >
          <option
            value="1"
            selected={effectiveValues.isActive !== false && effectiveValues.isActive !== "0"}
          >
            Active
          </option>
          <option
            value="0"
            selected={effectiveValues.isActive === false || effectiveValues.isActive === "0"}
          >
            Inactive
          </option>
        </select>
      </div>
    </div>

    <div class="flex justify-between items-center text-[11px] text-slate-400">
      <div class="space-y-1">
        <div>Created: {formatDateTime(option.createdAt)}</div>
        <div>Updated: {formatDateTime(option.updatedAt)}</div>
      </div>
    </div>

    <div class="flex justify-end gap-3 text-sm pt-2">
      <a
        href="/admin/options"
        class="px-4 py-2 rounded-lg border border-slate-700 hover:bg-slate-900"
      >
        Cancel
      </a>
      <button
        type="submit"
        class="px-4 py-2 rounded-lg bg-emerald-500 text-slate-950 font-semibold hover:bg-emerald-400"
      >
        Save changes
      </button>
    </div>
  </form>

  <!-- Danger zone -->
  <section class="rounded-xl border border-red-900 bg-red-950/40 p-6 space-y-3">
    <h2 class="text-sm font-semibold text-red-200">Danger zone</h2>
    <p class="text-xs text-red-100/80">
      Deleting this option will remove it from any tours that use it. This cannot be undone.
    </p>

    <form method="POST" action="?/delete" class="mt-2">
      <button
        type="submit"
        class="px-4 py-2 rounded-lg bg-red-600 text-slate-50 text-sm font-semibold hover:bg-red-500"
      >
        Delete option
      </button>
    </form>
  </section>
</div>
